apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "chart.fullname" .) }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http2
      appProtocol:  {{ if .Values.server.tls.enabled }}http2{{ else }}kubernetes.io/h2c{{ end }}
      protocol: TCP
      name: http2
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
