{{- if .Values.playground -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.db.password.secret.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  password: {{ randAlphaNum 16 | b64enc }}
{{- end }}