apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "platform.portName" . }}
      appProtocol:  {{ .Values.service.appProtocol | default (include "determine.appProtocol" .) }}
      protocol: TCP
      name: {{ include "platform.portName" . }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
