{{- if and (.Values.server.tls.enabled) (quote .Values.server.tls.secret | empty ) -}}
{{- $fullName := include "chart.fullname" . }}
{{- $serviceFQDN := printf "%s.%s.svc" $fullName .Release.Namespace }}
{{- $commonName := $serviceFQDN }}
{{- $sanList := list $fullName $serviceFQDN }}
{{- if and .Values.ingress.enabled  (gt (len .Values.ingress.hosts) 0) -}}
  {{- $hosts := list }}
  {{- range .Values.ingress.hosts }}
      {{- $hosts = append $hosts (toString .host) }}
  {{- end }}
  {{ $commonName := (index $hosts 0) }} 
  {{- $sanList = concat $sanList $hosts }}
{{- end }}
{{ $ipList := list }}
{{ $cert := genSelfSignedCert $commonName $ipList $sanList 365 }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "chart.fullname" . }}-tls
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
   "helm.sh/hook": pre-install
   "helm.sh/hook-delete-policy": before-hook-creation
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc  }}
{{- end }}

