name: Release Charts

on:
  release:
    types: [published]

jobs:
  release:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.AUTOMATION_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "opentdf-automation[bot]"
          git config user.email "123456789+opentdf-automation[bot]@users.noreply.github.com"

      - id: 'download-helm'
        shell: bash
        working-directory: '${{ runner.temp }}'
        env:
          HELM_VERSION: 'v3.14.4' # v3.14.4 = April 10 2024
          HELM_SHA256SUM: 'a5844ef2c38ef6ddf3b5a8f7d91e7e0e8ebc39a38bb3fc8013d629c1ef29c259'
        run: |
          curl -sSLO "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz"
          echo "${HELM_SHA256SUM}  helm-${HELM_VERSION}-linux-amd64.tar.gz" | sha256sum -c --quiet --strict
          mkdir -p helm
          tar xf "helm-${HELM_VERSION}-linux-amd64.tar.gz" -C helm
          mkdir -p "$HOME/.local/bin"
          mv ./helm/linux-amd64/helm "$HOME/.local/bin"

          helm version

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584
        env:
          CR_TOKEN: "${{ steps.app-token.outputs.token }}"
        with:
          skip_existing: true
          pages_branch: main

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e